services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: agendaclin
      POSTGRES_PASSWORD: agendaclin123
      POSTGRES_DB: agendaclin_db
    ports:
      - "5433:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data
volumes:
  dados_postgres: